name: Lint Checks
on: push
jobs:
  lint:
    name: Black
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements-test.txt
      - name: Check for black formatting
        run: black . --check
